//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIndexHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCode
    {
        public int DiscountID { get; set; }
        public string DiscountCode1 { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> Dollar { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> RoomTypeID { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
