//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIndexHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomInformation()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int RoomID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> RoomTypeID { get; set; }
        public string RoomNameCN { get; set; }
        public string RoomFacility { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<bool> IsLocking { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
