//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIndexHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.DiscountCode = new HashSet<DiscountCode>();
            this.HotelImg = new HashSet<HotelImg>();
            this.Orders = new HashSet<Orders>();
            this.RoomInformation = new HashSet<RoomInformation>();
            this.RoomTypeImg = new HashSet<RoomTypeImg>();
        }
    
        public int HotelID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string HotelNameEN { get; set; }
        public string HotelNameCN { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string AddressEN { get; set; }
        public string AddressCN { get; set; }
        public Nullable<decimal> StarRated { get; set; }
        public Nullable<int> TaxIDNumber { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string Description { get; set; }
        public string GoogleMapURL { get; set; }
        public Nullable<int> HotelTotalRoomQty { get; set; }
        public Nullable<decimal> CustomerRated { get; set; }
        public Nullable<bool> IsLocking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCode> DiscountCode { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelImg> HotelImg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomInformation> RoomInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomTypeImg> RoomTypeImg { get; set; }
    }
}
