//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIndexHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<int> RoomTypeID { get; set; }
        public string Payment { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string DiscountCode { get; set; }
        public string OrderState { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> OfferBreakfast { get; set; }
        public Nullable<int> AddBed { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> PayInfoID { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Members Members { get; set; }
        public virtual RoomType RoomType { get; set; }
        public virtual Orders Orders1 { get; set; }
        public virtual Orders Orders2 { get; set; }
        public virtual PayInfo PayInfo { get; set; }
        public virtual RoomInformation RoomInformation { get; set; }
    }
}
