//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIndexHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomType()
        {
            this.DiscountCode = new HashSet<DiscountCode>();
            this.Orders = new HashSet<Orders>();
            this.RoomInformation = new HashSet<RoomInformation>();
        }
    
        public int RoomTypeID { get; set; }
        public string RoomTypeNameEN { get; set; }
        public string RoomTypeNameCN { get; set; }
        public int RoomGuests { get; set; }
        public decimal UnitPrice_Normal { get; set; }
        public Nullable<decimal> UnitPrice_Holiday { get; set; }
        public Nullable<int> RoomQty { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<bool> CanAddBed { get; set; }
        public Nullable<bool> OfferBreakfast { get; set; }
        public Nullable<bool> IsLocking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCode> DiscountCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomInformation> RoomInformation { get; set; }
    }
}
